server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: aitest_repository
      username: aitest
      password: aitest
      port: 27017

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

# logging config
logging:
  config: classpath:logback.xml